const sql = require('../../database/queries');
const codeModel = require('./code');

let codeRepository = {
    findCodeById(id) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'SELECT code FROM code WHERE code = ' + id + ';'
            sql.query(queryCommand).then((response) => {
                resolve(response);
            });
        })
    },


    findLastAutoGeneratedCode() {
        return new Promise((resolve, reject) => {
            let queryCommand = 'SELECT code FROM code  WHERE  code LIKE "A%" ORDER BY id DESC LIMIT 0, 1;';
            sql.query(queryCommand).then((response) => {
                resolve(response);
            });
        })
    },

    createCode(value) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'INSERT INTO code (' + codeModel + ') VALUES (' + value + ')';
            sql.query(queryCommand).then(() => {
                queryCommand = 'SELECT MAX(id) as codeID FROM code;';
                sql.query(queryCommand).then((response) => {
                    resolve(response);
                })
            });
        })
    },

    editCode(values, id) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'UPDATE code SET ' + values + ' WHERE code.id = ' + id + ';'
            sql.query(queryCommand).then((response) => {
                resolve(response);
            });
        })    
    },

}

module.exports = codeRepository;