let sql = require('../../database/queries');
let codeModel = require('./code');

let clientRepository = {
    findCodeById(id) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'SELECT code FROM code WHERE code = ' + id + ';'
            sql.query(queryCommand).then((response) => {
                resolve(response);
            }, error => {
                console.log(error);
                reject();
            });
        })
    },


    findLastAutoGeneratedCode(id) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'SELECT code FROM code  WHERE  code LIKE "A%" ORDER BY id DESC LIMIT 0, 1;';
            sql.query(queryCommand).then((response) => {
                resolve(response);
            }, error => {
                console.log(error);
                reject();
            });
        })
    },

    createCode(value) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'INSERT INTO code (' + codeModel + ') VALUES (' + value + ')';
            sql.query(queryCommand).then((response) => {
                resolve(response);
            }, error => {
                console.log(error);
                reject();
            });
        })
    },

    editClient(values, code) {
        return new Promise((resolve, reject) => {
            let queryCommand = 'UPDATE code SET ' + values + ' WHERE code.code = ' + code.toString() +';'
            sql.query(queryCommand).then((response) => {
                resolve(response);
            }, error => {
                console.log(error);
                reject();
            });
        })    },

}

module.exports = clientRepository;